name = "bg-remover"
compatibility_date = "2024-01-01"

[build]
command = "cd frontend && npm run build"

pages_build_output_dir = "frontend/.next"

[vars]
REMOVE_BG_API_KEY = "w98ePuScjM2zVfpfQcVbSmR9"
